language: php

php:
    - '7.0'

before_script:
    - mv .env.travis .env
    - "mysql -e 'create database `steamhub`;'"
    - composer install -n --prefer-source
    - "php artisan key:generate"
    - php artisan migrate --seed -n

after_success:
    - "bash <(curl -s https://codecov.io/bash)"