language: php

php:
    - '7.0'

before_script:
    - mv .env.travis .env
    - "mysql -e 'create database `steamhub`;'"
    - composer install -n --prefer-source
    - composer require satooshi/php-coveralls
    - "php artisan key:generate"
    - php artisan migrate --seed -n
    - "php artisan db:seed"

after_success:
    - travis_retry php vendor/bin/coveralls
    - "bash <(curl -s https://codecov.io/bash)"